"""Add last_synced_at

Revision ID: 05772dc9c181
Revises: 1782b521ddf4
Create Date: 2026-01-24 17:03:28.784350

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05772dc9c181"
down_revision: Union[str, None] = "1782b521ddf4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "baseartifact", sa.Column("last_synced_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("baseartifact", "last_synced_at")
    # ### end Alembic commands ###
