"""Initial schema

Revision ID: 1782b521ddf4
Revises: 
Create Date: 2026-01-24 15:53:34.874804

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1782b521ddf4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "baseartifact",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "TRACE",
                "HYPOTHESIS",
                "ASSUMPTION",
                "EXPERIMENT",
                "OBSERVATION",
                "DECISION",
                "REFLECTION",
                name="artifacttype",
            ),
            nullable=False,
        ),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("research_phase", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ACTIVE",
                "COMPLETED",
                "FAILED_BUT_INFORMATIVE",
                "DEPRECATED",
                name="artifactstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.Enum("PRIVATE", "TEAM", "PUBLIC", name="artifactvisibility"),
            nullable=False,
        ),
        sa.Column("grace_period_end", sa.DateTime(), nullable=True),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("proposed_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("approved_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("metadata_blob", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("provenance_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_baseartifact_project_id"), "baseartifact", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_baseartifact_status"), "baseartifact", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_baseartifact_type"), "baseartifact", ["type"], unique=False
    )
    op.create_table(
        "artifactrelation",
        sa.Column("source_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("target_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("relation_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["baseartifact.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["baseartifact.id"],
        ),
        sa.PrimaryKeyConstraint("source_id", "target_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("artifactrelation")
    op.drop_index(op.f("ix_baseartifact_type"), table_name="baseartifact")
    op.drop_index(op.f("ix_baseartifact_status"), table_name="baseartifact")
    op.drop_index(op.f("ix_baseartifact_project_id"), table_name="baseartifact")
    op.drop_table("baseartifact")
    # ### end Alembic commands ###
