from typing import List
from apps.crl.core.models import BaseArtifact, ArtifactType

class ExportService:
    """Service for exporting research artifacts to publication-ready formats."""

    @staticmethod
    def to_markdown(artifacts: List[BaseArtifact], project_name: str) -> str:
        """Generates a Markdown draft of the research process."""
        md = f"# Research Draft: {project_name}\n\n"
        md += f"*Generated by RAE-CRL on {artifacts[0].created_at.strftime('%Y-%m-%d') if artifacts else 'N/A'}*\n\n"

        # Organize by type
        sections = {
            ArtifactType.HYPOTHESIS: "## 1. Hypotheses",
            ArtifactType.ASSUMPTION: "## 2. Theoretical Assumptions",
            ArtifactType.EXPERIMENT: "## 3. Experimental Methodology",
            ArtifactType.OBSERVATION: "## 4. Empirical Observations",
            ArtifactType.DECISION: "## 5. Strategic Decisions",
            ArtifactType.REFLECTION: "## 6. Reflections & Meta-Analysis",
        }

        for art_type, title in sections.items():
            type_artifacts = [a for f in [art_type] for a in artifacts if a.type == f]
            if type_artifacts:
                md += f"{title}\n\n"
                for art in type_artifacts:
                    md += f"### {art.title}\n"
                    md += f"{art.description}\n\n"
                    if art.metadata_blob:
                        md += "**Metadata:**\n"
                        for k, v in art.metadata_blob.items():
                            md += f"- *{k}*: {v}\n"
                        md += "\n"

        return md

    @staticmethod
    def to_latex(artifacts: List[BaseArtifact], project_name: str) -> str:
        """Generates a LaTeX draft of the research process."""
        tex = r"\documentclass{article}" + "\n"
        tex += r"\usepackage[utf8]{inputenc}" + "\n"
        tex += r"\title{Research Draft: " + project_name + "}\n"
        tex += r"\author{Generated by RAE-CRL}\n"
        tex += r"\begin{document}" + "\n"
        tex += r"\maketitle" + "\n\n"

        # Simple mapping to LaTeX sections
        sections = {
            ArtifactType.HYPOTHESIS: r"\section{Hypotheses}",
            ArtifactType.ASSUMPTION: r"\section{Theoretical Assumptions}",
            ArtifactType.EXPERIMENT: r"\section{Experimental Methodology}",
            ArtifactType.OBSERVATION: r"\section{Empirical Observations}",
            ArtifactType.DECISION: r"\section{Strategic Decisions}",
            ArtifactType.REFLECTION: r"\section{Reflections \& Meta-Analysis}",
        }

        for art_type, section_cmd in sections.items():
            type_artifacts = [a for a in artifacts if a.type == art_type]
            if type_artifacts:
                tex += f"{section_cmd}\n\n"
                for art in type_artifacts:
                    tex += r"\subsection{" + art.title + "}\n"
                    tex += art.description.replace("_", r"\_").replace("&", r"\&") + "\n\n"

        tex += r"\end{document}"
        return tex
